from strategy.manager import Strategy
from strategy.carrier_madness import CarrierMadness
from strategy.macro import Macro
from strategy.stalker_proxy import StalkerProxy
from strategy.call_of_void import CallOfTheVoid
from strategy.two_base_colossus import TwoBaseColossus
from strategy.two_base_archons import TwoBaseArchons
from strategy.bio import Bio
from strategy.adept_proxy import AdeptProxy
from strategy.defend_rush import DefendRush
from strategy.stalker_defend import StalkerDefend
from strategy.dt import Dt
from strategy.blinkers import Blinkers
